# Generated by Django 3.1.2 on 2020-10-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unstarted_runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=0)),
                ('reg_number', models.CharField(default='XXX0000', max_length=10)),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startlists.race')),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=0)),
                ('old_reg_number', models.CharField(default='XXX0000', max_length=10)),
                ('old_firstname', models.CharField(default='', max_length=50)),
                ('old_lastname', models.CharField(default='', max_length=50)),
                ('old_sinumber', models.IntegerField()),
                ('new_reg_number', models.CharField(default='XXX0000', max_length=10)),
                ('new_firstname', models.CharField(default='', max_length=50)),
                ('new_lastname', models.CharField(default='', max_length=50)),
                ('new_sinumber', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startlists.race')),
            ],
        ),
    ]
