# Generated by Django 3.1.3 on 2020-12-03 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startlists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='key',
        ),
    ]
