# Generated by Django 3.1.3 on 2020-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startlists', '0002_remove_race_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
