# Generated by Django 3.1.3 on 2020-12-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startlists', '0003_auto_20201203_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change',
            name='start_time',
        ),
        migrations.AddField(
            model_name='change',
            name='new_start_time',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='change',
            name='old_start_time',
            field=models.CharField(default='00:00', max_length=20),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_sinumber',
            field=models.IntegerField(default=0),
        ),
    ]
